# Generated by Django 6.0.4 on 2026-04-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_phrase', models.CharField(max_length=500)),
                ('english_meaning', models.TextField()),
                ('nepali_meaning', models.TextField(blank=True)),
                ('pronunciation', models.CharField(blank=True, max_length=500)),
                ('context', models.CharField(max_length=50)),
                ('audio_file', models.FileField(blank=True, upload_to='audio/phrases/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=200)),
                ('english_meaning', models.TextField()),
                ('nepali_meaning', models.TextField(blank=True)),
                ('pronunciation', models.CharField(blank=True, max_length=200)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('example_sentence', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='audio/words/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
            ],
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('source_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='dictionary.word')),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phrases', models.ManyToManyField(blank=True, to='dictionary.phrase')),
                ('words', models.ManyToManyField(blank=True, to='dictionary.word')),
            ],
        ),
    ]
